backend/isoko-backend/package.json, backend/isoko-backend/template.yml
=> S3Bucket infrastructure setup

frontend/isoko/src/App.tsx, frontend/isoko/src/pages/Authentication/PasswordResetSuccess.tsx, frontend/isoko/src/pages/Authentication/ResetPassword.tsx
Implemented forgot password functionality and frontend flow and Cognito flow
=> Implemented Forgot Password Functionality

frontend/isoko/package-lock.json, frontend/isoko/package.json, frontend/isoko/src/components/businessPage/BusinessSidebar.tsx, frontend/isoko/src/pages/Business.tsx, frontend/isoko/src/styles/StyledButton.ts
=> Implement Business Sidebar Component

backend/isoko-backend/__tests__/unit/handlers/review/post-review.test.js, backend/isoko-backend/__tests__/unit/handlers/triggers/cognito-post-confirmation.test.js, backend/isoko-backend/src/handlers/review/post-review.js, backend/isoko-backend/src/handlers/triggers/cognito-post-confirmation.js, backend/isoko-backend/template.yml
View API Spec [here](https://docs.google.com/document/d/1OaJnNI6xu4Dx74xy1rtoQZQ6F0VpDDxGhN6RDlYOwac/edit#bookmark=id.l8hghll9tg2u).
View JIRA ticket [here](https://platinum.cscaws.com:8443/browse/IS-74)
- Added new endpoint for post review + tests.
- Only need to look at post-review.test.js, post-review.js, template.yml (the rest are just prettier format changes because I didn't run it on my other PR)
- Not fully deployed yet
=> Is 74 post review

backend/isoko-backend/template.yml
no longer need this code now that we have IsokoBackendApi
=> Fix deployment issue

backend/isoko-backend/__tests__/unit/handlers/business/get-business-page.test.js, backend/isoko-backend/__tests__/unit/handlers/business/get-search-results.test.js, backend/isoko-backend/__tests__/unit/handlers/business/post-list-business.test.js, backend/isoko-backend/__tests__/unit/handlers/business/put-edit-business-page.test.js, backend/isoko-backend/src/handlers/business/get-business-page.js, backend/isoko-backend/src/handlers/business/post-list-business.js, backend/isoko-backend/src/handlers/business/put-edit-business-page.js
implemented the following business endpoints with accompanying jest tests 
- POST /business/
- GET /business/:businessId
- PUT /business/:businessId
=> IS-62 misc business endpoints

backend/isoko-backend/__tests__/unit/handlers/review/get-user-reviews.test.js, backend/isoko-backend/__tests__/unit/handlers/triggers/cognito-post-confirmation.test.js, backend/isoko-backend/src/handlers/review/get-user-reviews.js, backend/isoko-backend/src/handlers/triggers/cognito-post-confirmation.js
- completed GET endpoint for user reviews + jest tests
- congito-post-confirmation.test.js (part of add user to dynamodb task) was failing when i ran 'npm test' --> error was "uncaught promise." added a try/catch around docClient call in congito-post-confirmation.js which fixed it so all tests are passing, but i think this is worth looking into because it wasn't failing previously and nothing about it changed (to my knowledge)
=> GET user/:userSub/reviews endpoint + tests

frontend/isoko/src/components/business/AboutTheOwner.tsx, frontend/isoko/src/pages/Business.tsx
JIRA Link [here](https://platinum.cscaws.com:8443/browse/IS-86).
Added About the Owner Component. Please let me know if there are ways I can improve the styling.
=> IS-86 About the Owner Component

frontend/isoko/src/App.tsx, frontend/isoko/src/components/Review.tsx, frontend/isoko/src/components/SignOutButton.tsx, frontend/isoko/src/components/business/KeywordTag.tsx, frontend/isoko/src/features/counter/counterAPI.ts, frontend/isoko/src/features/counter/counterSlice.ts, frontend/isoko/src/pages/Authentication/EmailVerificationStep.tsx, frontend/isoko/src/pages/Authentication/ForgotPassword.tsx, frontend/isoko/src/pages/Authentication/Login.tsx, frontend/isoko/src/pages/Authentication/PasswordResetSuccess.tsx, frontend/isoko/src/pages/Authentication/ResetPassword.tsx, frontend/isoko/src/pages/Authentication/SignUp.tsx, frontend/isoko/src/pages/Business.tsx, frontend/isoko/src/pages/BusinessDash.tsx, frontend/isoko/src/pages/Home.tsx, frontend/isoko/src/pages/ListBusiness.tsx, frontend/isoko/src/pages/ModDash.tsx, frontend/isoko/src/pages/Profile.tsx, frontend/isoko/src/pages/Search.tsx, frontend/isoko/src/pages/StyleExample.tsx, frontend/isoko/src/serviceWorker.ts
Very simple commit, just fixed all eslint issues
=> Fixed linter issues, we should ideally not merge any code in with lint issues moving forward.

frontend/isoko/src/pages/BusinessDashboard/BusinessDash.tsx
=> Business Sidebar & Root Component

backend/isoko-backend/__tests__/unit/handlers/business/post-search-results.test.js, backend/isoko-backend/package.json, backend/isoko-backend/src/handlers/business/post-search-results.js, backend/isoko-backend/template.yml
Fix various small bugs and update the endpoint to better match the changes to the API spec. Also added better error reporting.
=> Clean up POST /searchBusiness endpoint

frontend/isoko/src/components/business_dashboard/SortReviewsDropdown.tsx
literally just messed up the name of the component.
=> Fix Sort Reviews Dropdown

frontend/isoko/src/pages/BusinessDashboard/BusinessDash.tsx, frontend/isoko/src/pages/BusinessDashboard/UpdateInfo.tsx, frontend/isoko/src/pages/ListBusiness.tsx, frontend/isoko/src/pages/Search.tsx
Removed leftover headers from skeleton, fixed list business header on business dashboard
=> Clean up Page headers

frontend/isoko/src/components/reviews/Review.tsx, frontend/isoko/src/components/reviews/WriteReview.tsx, frontend/isoko/src/components/reviews/WriteReviewModal.tsx, frontend/isoko/src/pages/Business.tsx, frontend/isoko/src/pages/BusinessDashboard/Reviews.tsx
=> IS-94 Write review modal

frontend/isoko/package-lock.json, frontend/isoko/package.json, frontend/isoko/src/components/Home/SearchBar.tsx, frontend/isoko/src/pages/SearchResults.tsx, frontend/isoko/src/types/GlobalTypes.ts
Added loading spinner to search results page.
=> [IS-109] loading spinner search results

backend/isoko-backend/__tests__/unit/handlers/business/put-edit-business-page.test.js, backend/isoko-backend/__tests__/unit/handlers/photos/get-photo-url.test.js, backend/isoko-backend/src/constants.js, backend/isoko-backend/src/handlers/business/put-edit-business-page.js, backend/isoko-backend/src/handlers/photos/get-photo-url.js, backend/isoko-backend/src/handlers/util/response-utils.js
Fix PUT business endpoint, previously it would 502 error each time I hit it. Tested end-to-end
List of fixes:
* Updated to use correct DynamoDB request (key & response type)
* Updated to use correct field from DynamoDB response
* Update to send 400 responses instead of throwing an error
=> [IS-119] Fix PUT business endpoint

frontend/isoko/src/app/store.ts, frontend/isoko/src/features/business/BusinessAPI.ts, frontend/isoko/src/features/business/BusinessSlice.spec.js, frontend/isoko/src/features/business/BusinessSlice.ts, frontend/isoko/src/features/business/SearchResultsSlice.ts, frontend/isoko/src/pages/BusinessDashboard/Analytics.tsx, frontend/isoko/src/types/GlobalTypes.ts
Added Redux for business according to spec. Not end to end tested.
=> IS-110 Business Slice Redux

frontend/isoko/src/app/store.ts, frontend/isoko/src/features/profile/ProfileAPI.ts, frontend/isoko/src/features/profile/ProfileSlice.spec.js, frontend/isoko/src/features/profile/ProfileSlice.ts, frontend/isoko/src/types/GlobalTypes.ts
Implemented Profile Page Redux Slice according to spec. Was unable to do end-to-end testing since the endpoints are not merged in yet but it should work as long as those endpoints are built off of the two bug fix PR's I made.
=> [IS-112] Profile Page Redux Slice

frontend/isoko/src/App.tsx, frontend/isoko/src/components/HamburgerComponent.tsx, frontend/isoko/src/pages/Business.tsx, frontend/isoko/src/pages/Profile.tsx, frontend/isoko/src/pages/RestrictedModal.tsx
Added a "tHiS acTiOn iS bLOcKeD mODaL" to:
- leaving reviews
- accessing the profile page
- list a business page
- businessDashboard page
=> Is 115 add restrictive actions

frontend/isoko/src/components/Home/LocationSearchBar.tsx, frontend/isoko/src/features/counter/counterSlice.ts
See this for reasoning/context 
[https://docs.google.com/document/d/1wHwSnfhGvX4mHrXC8CoAqg6e0GOJEFCoXRy9e9qiGrk/edit?usp=sharing](url)
=> Is 108 location searchbar

frontend/isoko/package-lock.json, frontend/isoko/package.json, frontend/isoko/public/index.html, frontend/isoko/src/App.tsx
- created Google Analytics account (p sure this is associated w my Google acct, but shouldn't matter since we're just using react-ga/calling the API and won't really be using the dashboard) 
- installed `react-ga`
- added tracking info to application 
- bare minimum testing with `localhost` (should be able to track with our deployed version once this is merged) 
lmk if there's anything else that needs to be done for this task! happy to continue w analytics in previous sprints to build on this
=> GA initial setup

frontend/isoko/src/pages/Business.tsx
Fixed Business Preview Responsiveness in Business Dash
=> IS-131 Fix Business Preview Responsiveness in Business Dash

backend/isoko-backend/__tests__/unit/handlers/business/get-business-page.test.js, backend/isoko-backend/__tests__/unit/handlers/business/post-list-business.test.js, backend/isoko-backend/src/handlers/business/get-business-page.js, backend/isoko-backend/src/handlers/business/post-list-business.js
Added missing response headers to post list business to stop 502 response code on successful request
=> Fix post list business

frontend/isoko/src/App.tsx, frontend/isoko/src/components/business/Business.tsx, frontend/isoko/src/components/business/BusinessPreview.tsx, frontend/isoko/src/pages/BusinessPage.tsx, frontend/isoko/src/pages/SearchResults.tsx
Clicking on a business in the search results page will now take you to a business page with properly populated fields. The page also has a route based on the business Id. 
Also added a loading spinner to make sure the page is fully populated before we go to it.
=> IS-122 Link Business Click to Backend

frontend/isoko/package-lock.json, frontend/isoko/package.json, frontend/isoko/src/components/business/Business.tsx, frontend/isoko/src/components/business_dashboard/RatingGraph.tsx, frontend/isoko/src/components/business_dashboard/Stat.tsx, frontend/isoko/src/pages/BusinessDashboard/Analytics.tsx
created top half of analytics page ("general analytics" and "ratings breakdown") and installed [recharts](https://recharts.org/en-US) per rohith's suggestion, everything is currently populated with dummy data. upon approval, will link with IS-125 (google analytics event logging) to populate with data from google analytics
=> Is 104 analytics frontend

frontend/isoko/src/components/Home/SearchBar.tsx, frontend/isoko/src/components/business/Business.tsx, frontend/isoko/src/components/search/AddTagModal.tsx, frontend/isoko/src/features/business/SearchResultsSlice.spec.js, frontend/isoko/src/features/business/SearchResultsSlice.ts, frontend/isoko/src/pages/SearchResults.tsx
Fixed "Any Minority Owned" bug so now when use doesn't select any tags to search by the "Any Minority Owned" tag is auto-selected. Also no longer allow users to select "Any Minority Owned" tag alongside another tag.
=> [IS-137] Fix "Any Minority Owned" bug

frontend/isoko/src/constants/constants.ts, frontend/isoko/src/features/business/SearchResultsAPI.ts, frontend/isoko/src/features/business/SearchResultsSlice.spec.js, frontend/isoko/src/features/business/SearchResultsSlice.ts, frontend/isoko/src/pages/SearchResults.tsx, frontend/isoko/src/types/GlobalTypes.ts
Updated frontend to use new search results response format to display both brick & mortar results as well as online results.
* Updated redux to use new format
* Updated SearchResults page to use new format
=> [IS-123] Display online search results on frontend

frontend/isoko/package-lock.json, frontend/isoko/package.json
i am going to laugh so hard if this works
=> hit em w the npm install

frontend/isoko/src/components/HamburgerComponent.tsx
This PR addresses a few things: 
- Only show business dashboard to logged in users that are business owners
- Show signup/login to users that aren't logged in
- Change Sign Up to Signup/Login and change routing to signup
- Add Sign out option for logged in users
=> IS-144/145 Fix Hamburger Component

frontend/isoko/src/components/business/Business.tsx, frontend/isoko/src/components/business/BusinessSidebar.tsx, frontend/isoko/src/components/business/ClaimBusinessModal.tsx, frontend/isoko/src/features/profile/ProfileAPI.ts, frontend/isoko/src/features/profile/ProfileSlice.spec.js, frontend/isoko/src/features/profile/ProfileSlice.ts, frontend/isoko/src/pages/BusinessPage.tsx
- added front end for claiming business
- ensures proper authentication
- added function to profile slice + tests to update user to business owner + what business they own
- updating the business with about owner information request is sent properly but there is a bug in the lambda to edit the business page that is causing a 502
=> IS 132 Claim Business Modal

frontend/isoko/src/components/reviews/WriteReviewModal.tsx
- using write review modal updates # reviews and # stars in Businesses and SearchResults
=> fix review posting

frontend/isoko/src/components/business/Business.tsx, frontend/isoko/src/components/business/ClaimBusinessModal.tsx, frontend/isoko/src/pages/BusinessDashboard/Analytics.tsx, frontend/isoko/src/pages/BusinessDashboard/BusinessDash.tsx, frontend/isoko/src/pages/BusinessDashboard/Reviews.tsx, frontend/isoko/src/pages/BusinessDashboard/UpdateInfo.tsx, frontend/isoko/src/pages/Home.tsx, frontend/isoko/src/pages/ListBusiness.tsx
Fixed the bugs with the claim a business flow. Also made the order of the hours listed in the businessSidebar component consistent with the order of hours listed in UpdateInfo/ListBusiness component.
**PUT edit business still doesn't work with all the field and idk why for sure. It might have something to do with DynamoDB not already having an empty object for aboutOwner defined. But this will work for the purposes of our demo.
=> Fixed claim a business flow
